### ISSUE TITLE
FR - custom title and desc for "error" urls

### ISSUE THREAD

**Issue by Jimmi08** [Moc/wrapper#16]
Wrong urls are urls without wrapper ID or with wrong ID

Actual state:
- with e_DEBUG error message (red) is displayed and title Wrapper

Needed:
- customized title
- customized message - without message box in not debug mode

**Comment by Moc** [comment]
Debug mode is for debugging (ie. solving bugs), not for general usage. 

In what kind of scenarios do you want to display customized titles & messages?

**Comment by Jimmi08** [comment]
https://www.e107sk.com/documentation/

it doesn't display title because weird theme behaviour, it is not intention...    I will fix it sometimes.

**Comment by Moc** [comment]
Thanks for the link but can you describe the scenarios in which you would want to display custom titles (other than already defined in the wrapper itself) and custom messages when for example?

**Comment by Jimmi08** [comment]
This is for error URLs so no titles from wrapper itself can be used (wrapper is not existing, but url is)

**Comment by Moc** [comment]
So in case the wrapper ID does not exist (or isn't entered) you want to display no caption? Do I understand that correctly?

**Comment by Jimmi08** [comment]
Not fully :)
This is wrapper url, everything is ok
/documentation/2/e107-developer-guide
this work too
/documentation/2/
but
this was returning ugly error and it is not error in fact, it is plugin frontpage. 
/documentation/

That error shouldn't be there. It is not error, that page exists just without content. 
I added content just to use existing link.

**Comment by Moc** [comment]
I've made some changes:
- In case of errors, the caption now is `LAN_ERROR`  (instead of `LAN_WRAPPER_NAME`)
- In case no id is entered (`yourwebsite.com/wrapper/` or `alias`), the error `LAN_WRAPPER_ERR1` is shown. 

Now I think I understand your goal: add a custom "homepage" for the wrapper plugin (in your case a landing page for all documentation). I'll think about if I'll add it to the plugin. I'll get back to you on this.
