### ISSUE TITLE
IP & Port

### ISSUE THREAD

**Issue by LaocheXe** [Moc/wrapper#8]
I help run a gaming community, which utilizes a bunch of random things. One thing is Firedaemon Fusion which is a web based control panel for a server - tried putting in the address - http://ds1.501stlegion-a3.com:20604

Nothing is shown in the wrapper - I removed the http:// and get "The Address Wasn't Understood" error

I don't know if it's a port issue - or that my site runs on https, and the Firedaemon Fusion is only http

**Comment by Moc** [comment]
This is related to http vs https. On a https website, you can not load http content, simply because it is not secured.  This is unrelated to the Wrapper plugin or e107 in general. 

Your browser console will also give you this error: 

```
 Content: The page at 'https://www.yourwebsite.com/wrapper/1' was loaded over HTTPS, but requested an insecure resource 'http://ds1.501stlegion-a3.com:20604/'. This request has been blocked; the content must be served over HTTPS.
```

There's nothing I can do to help solve this unfortunately. You'll either have to move Firedaemon to use https, which is a pretty basic requirement and important as well. Or you have to downgrade your website to use http only, which is a serious security issue.
